--
-- Name: roles; Type: TABLE; Schema: public; Owner: dbmanager
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.roles OWNER TO dbmanager;

--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: dbmanager
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);
	
--
-- Name: roles uk_k119kaqyutqcshswwho01bs9e; Type: CONSTRAINT; Schema: public; Owner: dbmanager
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_uk UNIQUE (id, name);

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: dbmanager
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: users; Type: TABLE; Schema: public; Owner: dbmanager
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    bet_balance bigint,
    email character varying(255),
    email_confirmed boolean,
    free_balance bigint,
    enabled boolean,
    os character varying(255),
    password character varying(255),
    phone character varying(255),
    withdrawal_balance bigint
);


ALTER TABLE public.users OWNER TO dbmanager;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: dbmanager
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: dbmanager
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_uk_email UNIQUE (email);


--
-- Name: users uk_5wpcaw3c6uf9qbbb8avvfh3xm; Type: CONSTRAINT; Schema: public; Owner: dbmanager
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_uk_id_email UNIQUE (id, email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: dbmanager
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: dbmanager
--

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    user_email character varying(255) NOT NULL,
    role_id bigint NOT NULL,
    role_name character varying(255) NOT NULL
);


ALTER TABLE public.user_roles OWNER TO dbmanager;

--
-- Name: users_verification_code; Type: TABLE; Schema: public; Owner: dbmanager
--

CREATE TABLE public.users_verification_code (
    id bigint NOT NULL,
    attemps integer,
    check_code integer,
    create_date timestamp without time zone,
    delay_date timestamp without time zone,
    expired_date timestamp without time zone,
    user_email character varying(255)
);


ALTER TABLE public.users_verification_code OWNER TO dbmanager;

--
-- Name: users_verification_code_id_seq; Type: SEQUENCE; Schema: public; Owner: dbmanager
--

ALTER TABLE public.users_verification_code ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_verification_code_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_verification_code users_verification_code_pkey; Type: CONSTRAINT; Schema: public; Owner: dbmanager
--

ALTER TABLE ONLY public.users_verification_code
    ADD CONSTRAINT users_verification_code_pkey PRIMARY KEY (id);

--
-- PostgreSQL database dump complete
--