--
-- Name: instrument; Type: TABLE; Schema: public; Owner: dbmanager
--

CREATE TABLE public.instrument (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    ask_price double precision,
    bid_price double precision,
    high_price double precision,
    last_price double precision,
    low_price double precision,
    symbol_name character varying(255)
);

ALTER TABLE public.instrument OWNER TO dbmanager;

--
-- Name: instrument instrument_pkey; Type: CONSTRAINT; Schema: public; Owner: dbmanager
--

ALTER TABLE ONLY public.instrument
    ADD CONSTRAINT instrument_pkey PRIMARY KEY (id);

--
-- Name: instrument_id_seq; Type: SEQUENCE; Schema: public; Owner: dbmanager
--

ALTER TABLE public.instrument ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.instrument_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: quote_bin_five_minute; Type: TABLE; Schema: public; Owner: dbmanager
--

CREATE TABLE public.quote_bin_five_minute (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    ask_price double precision,
    bid_price double precision,
    symbol_name character varying(255),
    "timestamp" timestamp without time zone
);

ALTER TABLE public.quote_bin_five_minute OWNER TO dbmanager;

--
-- Name: quote_bin_five_minute quote_bin_five_minute_pkey; Type: CONSTRAINT; Schema: public; Owner: dbmanager
--

ALTER TABLE ONLY public.quote_bin_five_minute
    ADD CONSTRAINT quote_bin_five_minute_pkey PRIMARY KEY (id);

--
-- Name: quote_bin_five_minute_id_seq; Type: SEQUENCE; Schema: public; Owner: dbmanager
--

ALTER TABLE public.quote_bin_five_minute ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quote_bin_five_minute_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quote_bin_one_minute; Type: TABLE; Schema: public; Owner: dbmanager
--

CREATE TABLE public.quote_bin_one_minute (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    ask_price double precision,
    bid_price double precision,
    symbol_name character varying(255),
    "timestamp" timestamp without time zone
);


ALTER TABLE public.quote_bin_one_minute OWNER TO dbmanager;

--
-- Name: quote_bin_one_minute quote_bin_one_minute_pkey; Type: CONSTRAINT; Schema: public; Owner: dbmanager
--

ALTER TABLE ONLY public.quote_bin_one_minute
    ADD CONSTRAINT quote_bin_one_minute_pkey PRIMARY KEY (id);

--
-- Name: quote_bin_one_minute_id_seq; Type: SEQUENCE; Schema: public; Owner: dbmanager
--

ALTER TABLE public.quote_bin_one_minute ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quote_bin_one_minute_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
